name: "Main Sync"
description: "Syncs main branch to next"

runs:
  using: "composite"
  steps:
    - name: Sync main to the next
      run: yarn run main-sync
      shell: bash
      env:
        REF: ${{ github.ref }}
        GH_TOKEN: ${{ github.token }}
