name: "Post Release"
description: "Runs the post-release flow"

runs:
  using: "composite"
  steps:
    - name: Install execa
      run: yarn global add execa
      shell: bash
    - name: Post Release
      run: yarn run post-release-prod
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
