name: Deploy
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      PAT:
        description: 'Add a PAT to secrets.'
        required: true
      VERCEL_ORG_ID:
        description: 'Add a VERCEL_ORG_ID to secrets.'
        required: true
      VERCEL_TOKEN:
        description: 'Add a VERCEL_TOKEN to secrets.'
        required: true
      VERCEL_PROJECT_WIDGET_CONFIG:
        description: 'Add a VERCEL_PROJECT_WIDGET_CONFIG to secrets.'
        required: true
      VERCEL_PROJECT_WIDGET_APP:
        description: 'Add a VERCEL_PROJECT_WIDGET_APP to secrets.'
        required: true
      VERCEL_PROJECT_STORYBOOK:
        description: 'Add a VERCEL_PROJECT_STORYBOOK to secrets.'
        required: true
      VERCEL_PROJECT_Q:
        description: 'Add a VERCEL_PROJECT_Q to secrets.'
        required: true
jobs:
  deploy-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Deploy packages
        run: |
          yarn global add vercel
          yarn run deploy
        env:
          REF: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_WIDGET_CONFIG: ${{ secrets.VERCEL_PROJECT_WIDGET_CONFIG }}
          VERCEL_PROJECT_WIDGET_APP: ${{ secrets.VERCEL_PROJECT_WIDGET_APP }}
          VERCEL_PROJECT_STORYBOOK: ${{ secrets.VERCEL_PROJECT_STORYBOOK }}
          VERCEL_PROJECT_Q: ${{ secrets.VERCEL_PROJECT_Q }}