name: Main Sync
on:
  workflow_dispatch:

  workflow_call:
    secrets:
      NPM_TOKEN:
        description: 'You need a npm token to be set.'
        required: true
      PAT:
        description: 'Add a PAT to secrets.'
        required: true
jobs:
  main-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Sync main to the next
        run: yarn run main-sync
        env:
          REF: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}
          # Github will create .npmrc based on this env variable.
          # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
