name: Production Release
on:
  workflow_dispatch:

jobs:
  sync-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Run Sync Main
        uses: ./.github/actions/sync-main

  publish:
    needs: sync-main
    uses: ./.github/workflows/publish.yml
    secrets: inherit

  deploy:
    needs: publish
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  post-release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Run Sync Next
        uses: ./.github/actions/sync-net