name: Production Release
on:
  workflow_dispatch:

jobs:
  main-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Run Main Sync
        uses: ./.github/actions/main-sync

  publish:
    needs: main-sync
    uses: ./.github/workflows/publish.yml
    secrets: inherit

  deploy:
    needs: publish
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  post-release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Run Post Release
        uses: ./.github/actions/post-release